import https from "https";
import fs from "fs/promises";
import path from "path";

function fetchText(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    https
      .get(url, { headers: { "User-Agent": "TickerGuessr/1.0 (pool builder)" } }, (res) => {
        let data = "";
        res.on("data", (c) => (data += c));
        res.on("end", () => resolve(data));
        res.on("error", reject);
      })
      .on("error", reject);
  });
}

function normalizeTicker(raw: string): string {
  return raw.trim().toUpperCase().replace(/[-/]/g, ".");
}

// Strip HTML tags/entities from a Wikipedia table cell.
function clean(cell: string): string {
  return cell
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&#0?39;/g, "'")
    .replace(/&quot;/g, '"')
    .trim();
}

interface PoolEntry { ticker: string; name: string; sector: string }

// Parse wikitables on the page; scans all tables and uses the first one whose
// headers match the requested columns. This tolerates layout shifts that add
// new tables before the constituent table.
function parseWikiTable(
  html: string,
  cols: { ticker: string; name: string; sector: string }
): PoolEntry[] {
  const tableMatches = Array.from(html.matchAll(/<table[^>]*class="[^"]*wikitable[^"]*"[\s\S]*?<\/table>/g));
  if (!tableMatches.length) throw new Error("no wikitable found");

  let lastHeaderSeen = "";
  for (const tableMatch of tableMatches) {
    const table = tableMatch[0];
    const rows = table.match(/<tr[\s\S]*?<\/tr>/g) ?? [];
    if (!rows.length) continue;
    const header = ((rows[0] ?? "").match(/<th[\s\S]*?<\/th>/g) ?? []).map((h: string) => clean(h).toLowerCase());
    const idxOf = (label: string) => header.findIndex((h: string) => h.includes(label));
    const ti = idxOf(cols.ticker), ni = idxOf(cols.name), si = idxOf(cols.sector);
    lastHeaderSeen = header.join(" | ");
    if (ti < 0 || ni < 0 || si < 0) continue; // try next table

    const out: PoolEntry[] = [];
    for (const row of rows.slice(1)) {
      const cells = (row.match(/<t[dh][\s\S]*?<\/t[dh]>/g) ?? []).map(clean);
      if (cells.length <= Math.max(ti, ni, si)) continue;
      const ticker = normalizeTicker(cells[ti]);
      if (!/^[A-Z.]+$/.test(ticker)) continue;
      out.push({ ticker, name: cells[ni], sector: cells[si] || "Unknown" });
    }
    return out;
  }
  throw new Error(`header mismatch across all tables; last header seen: ${lastHeaderSeen}`);
}

async function main() {
  console.log("Fetching S&P 500 + Nasdaq-100 constituents...");
  const [sp, nd] = await Promise.all([
    fetchText("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"),
    fetchText("https://en.wikipedia.org/wiki/Nasdaq-100"),
  ]);

  const spEntries = parseWikiTable(sp, { ticker: "symbol", name: "security", sector: "gics sector" });
  const ndEntries = parseWikiTable(nd, { ticker: "ticker", name: "company", sector: "icb industry" });
  console.log(`S&P 500: ${spEntries.length}, Nasdaq-100: ${ndEntries.length}`);
  if (spEntries.length < 400) throw new Error("S&P 500 parse looks wrong (<400 rows)");
  if (ndEntries.length < 80) throw new Error("Nasdaq-100 parse looks wrong (<80 rows)");

  const map = new Map<string, PoolEntry>();
  // Dedupe by ticker. Insert Nasdaq-100 first, then S&P, so the ~80 overlap
  // tickers keep S&P's GICS sector; Nasdaq-100-only names retain ICB industry.
  for (const e of [...ndEntries, ...spEntries]) map.set(e.ticker, e);
  const pool = Array.from(map.values()).sort((a, b) => a.ticker.localeCompare(b.ticker));
  console.log(`Pool (deduped): ${pool.length} tickers`);

  const output = [
    "// Generated by scripts/build-puzzle-pool.ts — do not edit manually.",
    "// Source: Wikipedia S&P 500 + Nasdaq-100 constituent tables. Recognizable large-caps.",
    "// Re-run: npx tsx scripts/build-puzzle-pool.ts",
    "export interface PoolEntry {",
    "  ticker: string;",
    "  name: string;",
    "  sector: string;",
    "}",
    "",
    `export const PUZZLE_POOL: PoolEntry[] = ${JSON.stringify(pool, null, 2)};`,
  ].join("\n");

  await fs.writeFile(path.join(process.cwd(), "src/data/puzzle-pool.ts"), output);
  console.log(`Wrote ${pool.length} entries to src/data/puzzle-pool.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
