import https from "https";
import fs from "fs/promises";
import path from "path";

async function fetchText(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    https
      .get(url, (res) => {
        let data = "";
        res.on("data", (c) => (data += c));
        res.on("end", () => resolve(data));
        res.on("error", reject);
      })
      .on("error", reject);
  });
}

// App convention is dot notation for share classes (BRK.B). Normalize any
// dash/slash separators the source uses to a dot.
function normalizeTicker(raw: string): string {
  return raw.trim().toUpperCase().replace(/[-/]/g, ".");
}

function parseNasdaqListed(text: string): Array<{ ticker: string; name: string }> {
  return text
    .trim()
    .split("\n")
    .slice(1)
    .filter((line) => {
      const cols = line.split("|");
      if (cols.length < 8) return false;
      const [, , , testIssue, , , etf] = cols;
      return etf === "N" && testIssue === "N";
    })
    .map((line) => {
      const cols = line.split("|");
      return {
        ticker: normalizeTicker(cols[0]),
        name: cols[1].replace(/ Common Stock.*/, "").replace(/ - Class [A-Z]$/, "").trim(),
      };
    });
}

function parseOtherListed(text: string): Array<{ ticker: string; name: string }> {
  return text
    .trim()
    .split("\n")
    .slice(1)
    .filter((line) => {
      const cols = line.split("|");
      if (cols.length < 7) return false;
      return cols[4] === "N" && cols[6] === "N"; // ETF=N, testIssue=N
    })
    .map((line) => {
      const cols = line.split("|");
      return {
        ticker: normalizeTicker(cols[0]),
        name: cols[1]
          .replace(/ Common Stock.*/, "")
          .replace(/ - Class [A-Z]$/, "")
          .trim(),
      };
    });
}

async function main() {
  console.log("Fetching NASDAQ + NYSE symbol files...");
  const [nasdaqText, otherText] = await Promise.all([
    fetchText("https://www.nasdaqtrader.com/dynamic/SymDir/nasdaqlisted.txt"),
    fetchText("https://www.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt"),
  ]);

  const map = new Map<string, string>();
  for (const c of [...parseOtherListed(otherText), ...parseNasdaqListed(nasdaqText)]) {
    if (/^[A-Z.]+$/.test(c.ticker)) map.set(c.ticker, c.name); // drop warrants/units with odd symbols
  }
  const companies = Array.from(map.entries())
    .map(([ticker, name]) => ({ ticker, name }))
    .sort((a, b) => a.ticker.localeCompare(b.ticker));

  const output = [
    'import { Company } from "../types/game";',
    "",
    "// Generated by scripts/build-company-list.ts — do not edit manually.",
    "// Source: NASDAQ + NYSE symbol files (ticker + name only). Broad autocomplete universe.",
    "// Re-run: npx tsx scripts/build-company-list.ts",
    `export const COMPANIES: Company[] = ${JSON.stringify(companies, null, 2)};`,
  ].join("\n");

  const outPath = path.join(process.cwd(), "src/data/companies.ts");
  await fs.writeFile(outPath, output + "\n");
  console.log(`Wrote ${companies.length} companies to src/data/companies.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
