// Generated by scripts/build-puzzle-pool.ts — do not edit manually.
// Source: Wikipedia S&P 500 + Nasdaq-100 constituent tables. Recognizable large-caps.
// Market cap tiers from api.nasdaq.com (undocumented, keyless).
// Re-run: npx tsx scripts/build-puzzle-pool.ts
export interface PoolEntry {
  ticker: string;
  name: string;
  sector: string;
  marketCapTier: string;
}

export const PUZZLE_POOL: PoolEntry[] = [
  {
    "ticker": "A",
    "name": "Agilent Technologies",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AAPL",
    "name": "Apple Inc.",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "ABBV",
    "name": "AbbVie",
    "sector": "Health Care",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "ABNB",
    "name": "Airbnb",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ABT",
    "name": "Abbott Laboratories",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ACGL",
    "name": "Arch Capital Group",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ACN",
    "name": "Accenture",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ADBE",
    "name": "Adobe Inc.",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ADI",
    "name": "Analog Devices",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ADM",
    "name": "Archer Daniels Midland",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ADP",
    "name": "Automatic Data Processing",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ADSK",
    "name": "Autodesk",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AEE",
    "name": "Ameren",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AEP",
    "name": "American Electric Power",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AES",
    "name": "AES Corporation",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AFL",
    "name": "Aflac",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AIG",
    "name": "American International Group",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AIZ",
    "name": "Assurant",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AJG",
    "name": "Arthur J. Gallagher & Co.",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AKAM",
    "name": "Akamai Technologies",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ALAB",
    "name": "Astera Labs",
    "sector": "Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ALB",
    "name": "Albemarle Corporation",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ALGN",
    "name": "Align Technology",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ALL",
    "name": "Allstate",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ALLE",
    "name": "Allegion",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ALNY",
    "name": "Alnylam Pharmaceuticals",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AMAT",
    "name": "Applied Materials",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "AMCR",
    "name": "Amcor",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AMD",
    "name": "Advanced Micro Devices",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "AME",
    "name": "Ametek",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AMGN",
    "name": "Amgen",
    "sector": "Health Care",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "AMP",
    "name": "Ameriprise Financial",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AMT",
    "name": "American Tower",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AMZN",
    "name": "Amazon",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "ANET",
    "name": "Arista Networks",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "AON",
    "name": "Aon plc",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AOS",
    "name": "A. O. Smith",
    "sector": "Industrials",
    "marketCapTier": "Mid Cap"
  },
  {
    "ticker": "APA",
    "name": "APA Corporation",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "APD",
    "name": "Air Products",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "APH",
    "name": "Amphenol",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "APO",
    "name": "Apollo Global Management",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "APP",
    "name": "AppLovin",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "APTV",
    "name": "Aptiv",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ARE",
    "name": "Alexandria Real Estate Equities",
    "sector": "Real Estate",
    "marketCapTier": "Mid Cap"
  },
  {
    "ticker": "ARES",
    "name": "Ares Management",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ARM",
    "name": "Arm Holdings",
    "sector": "Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "ASML",
    "name": "ASML Holding",
    "sector": "Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "ATO",
    "name": "Atmos Energy",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AVB",
    "name": "AvalonBay Communities",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AVGO",
    "name": "Broadcom",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "AVY",
    "name": "Avery Dennison",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AWK",
    "name": "American Water Works",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AXON",
    "name": "Axon Enterprise",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "AXP",
    "name": "American Express",
    "sector": "Financials",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "AZO",
    "name": "AutoZone",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BA",
    "name": "Boeing",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BAC",
    "name": "Bank of America",
    "sector": "Financials",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "BALL",
    "name": "Ball Corporation",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BAX",
    "name": "Baxter International",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BBY",
    "name": "Best Buy",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BDX",
    "name": "Becton Dickinson",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BEN",
    "name": "Franklin Resources",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BF.B",
    "name": "Brown–Forman",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BG",
    "name": "Bunge Global",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BIIB",
    "name": "Biogen",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BKNG",
    "name": "Booking Holdings",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BKR",
    "name": "Baker Hughes",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BLDR",
    "name": "Builders FirstSource",
    "sector": "Industrials",
    "marketCapTier": "Mid Cap"
  },
  {
    "ticker": "BLK",
    "name": "BlackRock",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BMY",
    "name": "Bristol Myers Squibb",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BNY",
    "name": "BNY Mellon",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BR",
    "name": "Broadridge Financial Solutions",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BRK.B",
    "name": "Berkshire Hathaway",
    "sector": "Financials",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "BRO",
    "name": "Brown & Brown",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BSX",
    "name": "Boston Scientific",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BX",
    "name": "Blackstone Inc.",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "BXP",
    "name": "BXP, Inc.",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "C",
    "name": "Citigroup",
    "sector": "Financials",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "CAH",
    "name": "Cardinal Health",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CARR",
    "name": "Carrier Global",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CASY",
    "name": "Casey's",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CAT",
    "name": "Caterpillar Inc.",
    "sector": "Industrials",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "CB",
    "name": "Chubb Limited",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CBOE",
    "name": "Cboe Global Markets",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CBRE",
    "name": "CBRE Group",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CCEP",
    "name": "Coca-Cola Europacific Partners",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CCI",
    "name": "Crown Castle",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CCL",
    "name": "Carnival Corporation",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CDNS",
    "name": "Cadence Design Systems",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CDW",
    "name": "CDW Corporation",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CEG",
    "name": "Constellation Energy",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CF",
    "name": "CF Industries",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CFG",
    "name": "Citizens Financial Group",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CHD",
    "name": "Church & Dwight",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CHRW",
    "name": "C.H. Robinson",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CHTR",
    "name": "Charter Communications",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CI",
    "name": "Cigna",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CIEN",
    "name": "Ciena",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CINF",
    "name": "Cincinnati Financial",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CL",
    "name": "Colgate-Palmolive",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CLX",
    "name": "Clorox",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CMCSA",
    "name": "Comcast",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CME",
    "name": "CME Group",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CMG",
    "name": "Chipotle Mexican Grill",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CMI",
    "name": "Cummins",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CMS",
    "name": "CMS Energy",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CNC",
    "name": "Centene Corporation",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CNP",
    "name": "CenterPoint Energy",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "COF",
    "name": "Capital One",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "COHR",
    "name": "Coherent Corp.",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "COIN",
    "name": "Coinbase",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "COO",
    "name": "Cooper Companies (The)",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "COP",
    "name": "ConocoPhillips",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "COR",
    "name": "Cencora",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "COST",
    "name": "Costco",
    "sector": "Consumer Staples",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "CPAY",
    "name": "Corpay",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CPRT",
    "name": "Copart",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CPT",
    "name": "Camden Property Trust",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CRH",
    "name": "CRH plc",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CRL",
    "name": "Charles River Laboratories",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CRM",
    "name": "Salesforce",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CRWD",
    "name": "CrowdStrike",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CRWV",
    "name": "CoreWeave",
    "sector": "Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CSCO",
    "name": "Cisco",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "CSGP",
    "name": "CoStar Group",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CSX",
    "name": "CSX Corporation",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CTAS",
    "name": "Cintas",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CTSH",
    "name": "Cognizant",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CTVA",
    "name": "Corteva",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CVNA",
    "name": "Carvana",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CVS",
    "name": "CVS Health",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "CVX",
    "name": "Chevron Corporation",
    "sector": "Energy",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "D",
    "name": "Dominion Energy",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DAL",
    "name": "Delta Air Lines",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DASH",
    "name": "DoorDash",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DD",
    "name": "DuPont",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DDOG",
    "name": "Datadog",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DE",
    "name": "Deere & Company",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DECK",
    "name": "Deckers Brands",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DELL",
    "name": "Dell Technologies",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "DG",
    "name": "Dollar General",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DGX",
    "name": "Quest Diagnostics",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DHI",
    "name": "D. R. Horton",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DHR",
    "name": "Danaher Corporation",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DIS",
    "name": "Walt Disney Company (The)",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DLR",
    "name": "Digital Realty",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DLTR",
    "name": "Dollar Tree",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DOC",
    "name": "Healthpeak Properties",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DOV",
    "name": "Dover Corporation",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DOW",
    "name": "Dow Inc.",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DPZ",
    "name": "Domino's",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DRI",
    "name": "Darden Restaurants",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DTE",
    "name": "DTE Energy",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DUK",
    "name": "Duke Energy",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DVA",
    "name": "DaVita",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DVN",
    "name": "Devon Energy",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "DXCM",
    "name": "Dexcom",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EA",
    "name": "Electronic Arts",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EBAY",
    "name": "eBay Inc.",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ECHO",
    "name": "EchoStar",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ECL",
    "name": "Ecolab",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ED",
    "name": "Consolidated Edison",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EFX",
    "name": "Equifax",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EG",
    "name": "Everest Group",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EIX",
    "name": "Edison International",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EL",
    "name": "Estée Lauder Companies (The)",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ELV",
    "name": "Elevance Health",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EME",
    "name": "Emcor",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EMR",
    "name": "Emerson Electric",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EOG",
    "name": "EOG Resources",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EQIX",
    "name": "Equinix",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EQR",
    "name": "Equity Residential",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EQT",
    "name": "EQT Corporation",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ERIE",
    "name": "Erie Indemnity",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ES",
    "name": "Eversource Energy",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ESS",
    "name": "Essex Property Trust",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ETN",
    "name": "Eaton Corporation",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ETR",
    "name": "Entergy",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EVRG",
    "name": "Evergy",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EW",
    "name": "Edwards Lifesciences",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EXC",
    "name": "Exelon",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EXE",
    "name": "Expand Energy",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EXPD",
    "name": "Expeditors International",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EXPE",
    "name": "Expedia Group",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "EXR",
    "name": "Extra Space Storage",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "F",
    "name": "Ford Motor Company",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FANG",
    "name": "Diamondback Energy",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FAST",
    "name": "Fastenal",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FCX",
    "name": "Freeport-McMoRan",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FDS",
    "name": "FactSet",
    "sector": "Financials",
    "marketCapTier": "Mid Cap"
  },
  {
    "ticker": "FDX",
    "name": "FedEx",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FDXF",
    "name": "FedEx Freight",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FE",
    "name": "FirstEnergy",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FER",
    "name": "Ferrovial",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FFIV",
    "name": "F5, Inc.",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FICO",
    "name": "Fair Isaac",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FIS",
    "name": "Fidelity National Information Services",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FISV",
    "name": "Fiserv",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FITB",
    "name": "Fifth Third Bancorp",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FIX",
    "name": "Comfort Systems USA",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FLEX",
    "name": "Flex Ltd.",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FOX",
    "name": "Fox Corporation (Class B)",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FOXA",
    "name": "Fox Corporation (Class A)",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FRT",
    "name": "Federal Realty Investment Trust",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FSLR",
    "name": "First Solar",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FTNT",
    "name": "Fortinet",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "FTV",
    "name": "Fortive",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "GD",
    "name": "General Dynamics",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "GDDY",
    "name": "GoDaddy",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "GE",
    "name": "GE Aerospace",
    "sector": "Industrials",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "GEHC",
    "name": "GE HealthCare",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "GEN",
    "name": "Gen Digital",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "GEV",
    "name": "GE Vernova",
    "sector": "Industrials",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "GILD",
    "name": "Gilead Sciences",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "GIS",
    "name": "General Mills",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "GL",
    "name": "Globe Life",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "GLW",
    "name": "Corning Inc.",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "GM",
    "name": "General Motors",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "GNRC",
    "name": "Generac",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "GOOG",
    "name": "Alphabet Inc. (Class C)",
    "sector": "Communication Services",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "GOOGL",
    "name": "Alphabet Inc. (Class A)",
    "sector": "Communication Services",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "GPC",
    "name": "Genuine Parts Company",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "GPN",
    "name": "Global Payments",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "GRMN",
    "name": "Garmin",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "GS",
    "name": "Goldman Sachs",
    "sector": "Financials",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "GWW",
    "name": "W. W. Grainger",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HAL",
    "name": "Halliburton",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HAS",
    "name": "Hasbro",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HBAN",
    "name": "Huntington Bancshares",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HCA",
    "name": "HCA Healthcare",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HD",
    "name": "Home Depot (The)",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "HIG",
    "name": "Hartford (The)",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HII",
    "name": "Huntington Ingalls Industries",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HLT",
    "name": "Hilton Worldwide",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HON",
    "name": "Honeywell Technologies",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HONA",
    "name": "Honeywell Aerospace",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HOOD",
    "name": "Robinhood Markets",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HPE",
    "name": "Hewlett Packard Enterprise",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HPQ",
    "name": "HP Inc.",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HRL",
    "name": "Hormel Foods",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HSIC",
    "name": "Henry Schein",
    "sector": "Health Care",
    "marketCapTier": "Mid Cap"
  },
  {
    "ticker": "HST",
    "name": "Host Hotels & Resorts",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HSY",
    "name": "Hershey Company (The)",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HUBB",
    "name": "Hubbell Incorporated",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HUM",
    "name": "Humana",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "HWM",
    "name": "Howmet Aerospace",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "IBKR",
    "name": "Interactive Brokers",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "IBM",
    "name": "IBM",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "ICE",
    "name": "Intercontinental Exchange",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "IDXX",
    "name": "Idexx Laboratories",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "IEX",
    "name": "IDEX Corporation",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "IFF",
    "name": "International Flavors & Fragrances",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "INCY",
    "name": "Incyte",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "INTC",
    "name": "Intel",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "INTU",
    "name": "Intuit",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "INVH",
    "name": "Invitation Homes",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "IP",
    "name": "International Paper",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "IQV",
    "name": "IQVIA",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "IR",
    "name": "Ingersoll Rand",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "IRM",
    "name": "Iron Mountain",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ISRG",
    "name": "Intuitive Surgical",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "IT",
    "name": "Gartner",
    "sector": "Information Technology",
    "marketCapTier": "Mid Cap"
  },
  {
    "ticker": "ITW",
    "name": "Illinois Tool Works",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "IVZ",
    "name": "Invesco",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "J",
    "name": "Jacobs Solutions",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "JBHT",
    "name": "J.B. Hunt",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "JBL",
    "name": "Jabil",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "JCI",
    "name": "Johnson Controls",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "JKHY",
    "name": "Jack Henry & Associates",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "JNJ",
    "name": "Johnson & Johnson",
    "sector": "Health Care",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "JPM",
    "name": "JPMorgan Chase",
    "sector": "Financials",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "KDP",
    "name": "Keurig Dr Pepper",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "KEY",
    "name": "KeyCorp",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "KEYS",
    "name": "Keysight Technologies",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "KHC",
    "name": "Kraft Heinz",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "KIM",
    "name": "Kimco Realty",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "KKR",
    "name": "KKR & Co.",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "KLAC",
    "name": "KLA Corporation",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "KMB",
    "name": "Kimberly-Clark",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "KMI",
    "name": "Kinder Morgan",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "KO",
    "name": "Coca-Cola Company (The)",
    "sector": "Consumer Staples",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "KR",
    "name": "Kroger",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "KVUE",
    "name": "Kenvue",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "L",
    "name": "Loews Corporation",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "LDOS",
    "name": "Leidos",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "LEN",
    "name": "Lennar",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "LH",
    "name": "Labcorp",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "LHX",
    "name": "L3Harris",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "LII",
    "name": "Lennox International",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "LIN",
    "name": "Linde plc",
    "sector": "Materials",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "LITE",
    "name": "Lumentum",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "LLY",
    "name": "Lilly (Eli)",
    "sector": "Health Care",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "LMT",
    "name": "Lockheed Martin",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "LNT",
    "name": "Alliant Energy",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "LOW",
    "name": "Lowe's",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "LRCX",
    "name": "Lam Research",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "LULU",
    "name": "Lululemon Athletica",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "LUV",
    "name": "Southwest Airlines",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "LVS",
    "name": "Las Vegas Sands",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "LYB",
    "name": "LyondellBasell",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "LYV",
    "name": "Live Nation Entertainment",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MA",
    "name": "Mastercard",
    "sector": "Financials",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "MAA",
    "name": "Mid-America Apartment Communities",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MAR",
    "name": "Marriott International",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MAS",
    "name": "Masco",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MCD",
    "name": "McDonald's",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MCHP",
    "name": "Microchip Technology",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MCK",
    "name": "McKesson Corporation",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MCO",
    "name": "Moody's Corporation",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MDLZ",
    "name": "Mondelez International",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MDT",
    "name": "Medtronic",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MELI",
    "name": "Mercado Libre",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MET",
    "name": "MetLife",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "META",
    "name": "Meta Platforms",
    "sector": "Communication Services",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "MGM",
    "name": "MGM Resorts",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MKC",
    "name": "McCormick & Company",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MLM",
    "name": "Martin Marietta Materials",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MMM",
    "name": "3M",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MNST",
    "name": "Monster Beverage",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MO",
    "name": "Altria",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MOS",
    "name": "Mosaic Company (The)",
    "sector": "Materials",
    "marketCapTier": "Mid Cap"
  },
  {
    "ticker": "MPC",
    "name": "Marathon Petroleum",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MPWR",
    "name": "Monolithic Power Systems",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MRK",
    "name": "Merck & Co.",
    "sector": "Health Care",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "MRNA",
    "name": "Moderna",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MRSH",
    "name": "Marsh McLennan",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MRVL",
    "name": "Marvell Technology",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "MS",
    "name": "Morgan Stanley",
    "sector": "Financials",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "MSCI",
    "name": "MSCI Inc.",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MSFT",
    "name": "Microsoft",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "MSI",
    "name": "Motorola Solutions",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MSTR",
    "name": "MicroStrategy",
    "sector": "Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MTB",
    "name": "M&T Bank",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MTD",
    "name": "Mettler Toledo",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "MU",
    "name": "Micron Technology",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "NBIS",
    "name": "Nebius Group",
    "sector": "Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NCLH",
    "name": "Norwegian Cruise Line Holdings",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Mid Cap"
  },
  {
    "ticker": "NDAQ",
    "name": "Nasdaq, Inc.",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NDSN",
    "name": "Nordson Corporation",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NEE",
    "name": "NextEra Energy",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NEM",
    "name": "Newmont",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NFLX",
    "name": "Netflix",
    "sector": "Communication Services",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "NI",
    "name": "NiSource",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NKE",
    "name": "Nike, Inc.",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NOC",
    "name": "Northrop Grumman",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NOW",
    "name": "ServiceNow",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NRG",
    "name": "NRG Energy",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NSC",
    "name": "Norfolk Southern",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NTAP",
    "name": "NetApp",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NTRS",
    "name": "Northern Trust",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NUE",
    "name": "Nucor",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NVDA",
    "name": "Nvidia",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "NVR",
    "name": "NVR, Inc.",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NWS",
    "name": "News Corp (Class B)",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NWSA",
    "name": "News Corp (Class A)",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "NXPI",
    "name": "NXP Semiconductors",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "O",
    "name": "Realty Income",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ODFL",
    "name": "Old Dominion",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "OKE",
    "name": "Oneok",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "OMC",
    "name": "Omnicom Group",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ON",
    "name": "ON Semiconductor",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ORCL",
    "name": "Oracle Corporation",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "ORLY",
    "name": "O’Reilly Automotive",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "OTIS",
    "name": "Otis Worldwide",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "OXY",
    "name": "Occidental Petroleum",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PANW",
    "name": "Palo Alto Networks",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "PAYX",
    "name": "Paychex",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PCAR",
    "name": "Paccar",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PCG",
    "name": "PG&E Corporation",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PDD",
    "name": "PDD Holdings",
    "sector": "Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PEG",
    "name": "Public Service Enterprise Group",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PEP",
    "name": "PepsiCo",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PFE",
    "name": "Pfizer",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PFG",
    "name": "Principal Financial Group",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PG",
    "name": "Procter & Gamble",
    "sector": "Consumer Staples",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "PGR",
    "name": "Progressive Corporation",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PH",
    "name": "Parker Hannifin",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PHM",
    "name": "PulteGroup",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PKG",
    "name": "Packaging Corporation of America",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PLD",
    "name": "Prologis",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PLTR",
    "name": "Palantir Technologies",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "PM",
    "name": "Philip Morris International",
    "sector": "Consumer Staples",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "PNC",
    "name": "PNC Financial Services",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PNR",
    "name": "Pentair",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PNW",
    "name": "Pinnacle West Capital",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PODD",
    "name": "Insulet Corporation",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PPG",
    "name": "PPG Industries",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PPL",
    "name": "PPL Corporation",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PRU",
    "name": "Prudential Financial",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PSA",
    "name": "Public Storage",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PSKY",
    "name": "Paramount Skydance Corporation",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PSX",
    "name": "Phillips 66",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PTC",
    "name": "PTC Inc.",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PWR",
    "name": "Quanta Services",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "PYPL",
    "name": "PayPal",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "Q",
    "name": "Qnity Electronics",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "QCOM",
    "name": "Qualcomm",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "RCL",
    "name": "Royal Caribbean Group",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "REG",
    "name": "Regency Centers",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "REGN",
    "name": "Regeneron Pharmaceuticals",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "RF",
    "name": "Regions Financial Corporation",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "RJF",
    "name": "Raymond James Financial",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "RKLB",
    "name": "Rocket Lab",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "RL",
    "name": "Ralph Lauren Corporation",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "RMD",
    "name": "ResMed",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ROK",
    "name": "Rockwell Automation",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ROL",
    "name": "Rollins, Inc.",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ROP",
    "name": "Roper Technologies",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ROST",
    "name": "Ross Stores",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "RSG",
    "name": "Republic Services",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "RTX",
    "name": "RTX Corporation",
    "sector": "Industrials",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "RVTY",
    "name": "Revvity",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SBAC",
    "name": "SBA Communications",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SBUX",
    "name": "Starbucks",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SCHW",
    "name": "Charles Schwab Corporation",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SHOP",
    "name": "Shopify",
    "sector": "Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SHW",
    "name": "Sherwin-Williams",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SJM",
    "name": "J.M. Smucker Company (The)",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SLB",
    "name": "Schlumberger",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SMCI",
    "name": "Supermicro",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SNA",
    "name": "Snap-on",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SNDK",
    "name": "Sandisk",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "SNPS",
    "name": "Synopsys",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SO",
    "name": "Southern Company",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SOLV",
    "name": "Solventum",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SPG",
    "name": "Simon Property Group",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SPGI",
    "name": "S&P Global",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SRE",
    "name": "Sempra",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "STE",
    "name": "Steris",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "STLD",
    "name": "Steel Dynamics",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "STT",
    "name": "State Street Corporation",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "STX",
    "name": "Seagate Technology",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "STZ",
    "name": "Constellation Brands",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SW",
    "name": "Smurfit Westrock",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SWK",
    "name": "Stanley Black & Decker",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SWKS",
    "name": "Skyworks Solutions",
    "sector": "Information Technology",
    "marketCapTier": "Mid Cap"
  },
  {
    "ticker": "SYF",
    "name": "Synchrony Financial",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SYK",
    "name": "Stryker Corporation",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "SYY",
    "name": "Sysco",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "T",
    "name": "AT&T",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TAP",
    "name": "Molson Coors Beverage Company",
    "sector": "Consumer Staples",
    "marketCapTier": "Mid Cap"
  },
  {
    "ticker": "TDG",
    "name": "TransDigm Group",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TDY",
    "name": "Teledyne Technologies",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TECH",
    "name": "Bio-Techne",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TEL",
    "name": "TE Connectivity",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TER",
    "name": "Teradyne",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TFC",
    "name": "Truist Financial",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TGT",
    "name": "Target Corporation",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TJX",
    "name": "TJX Companies",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TKO",
    "name": "TKO Group Holdings",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TMO",
    "name": "Thermo Fisher Scientific",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TMUS",
    "name": "T-Mobile US",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TPL",
    "name": "Texas Pacific Land Corporation",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TPR",
    "name": "Tapestry, Inc.",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TRGP",
    "name": "Targa Resources",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TRI",
    "name": "Thomson Reuters",
    "sector": "Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TRMB",
    "name": "Trimble Inc.",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TROW",
    "name": "T. Rowe Price",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TRV",
    "name": "Travelers Companies (The)",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TSCO",
    "name": "Tractor Supply",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TSLA",
    "name": "Tesla, Inc.",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "TSN",
    "name": "Tyson Foods",
    "sector": "Consumer Staples",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TT",
    "name": "Trane Technologies",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TTD",
    "name": "Trade Desk (The)",
    "sector": "Communication Services",
    "marketCapTier": "Mid Cap"
  },
  {
    "ticker": "TTWO",
    "name": "Take-Two Interactive",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TXN",
    "name": "Texas Instruments",
    "sector": "Information Technology",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "TXT",
    "name": "Textron",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "TYL",
    "name": "Tyler Technologies",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "UAL",
    "name": "United Airlines Holdings",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "UBER",
    "name": "Uber",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "UDR",
    "name": "UDR, Inc.",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "UHS",
    "name": "Universal Health Services",
    "sector": "Health Care",
    "marketCapTier": "Mid Cap"
  },
  {
    "ticker": "ULTA",
    "name": "Ulta Beauty",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "UNH",
    "name": "UnitedHealth Group",
    "sector": "Health Care",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "UNP",
    "name": "Union Pacific Corporation",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "UPS",
    "name": "United Parcel Service",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "URI",
    "name": "United Rentals",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "USB",
    "name": "U.S. Bancorp",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "V",
    "name": "Visa Inc.",
    "sector": "Financials",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "VEEV",
    "name": "Veeva Systems",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "VICI",
    "name": "Vici Properties",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "VLO",
    "name": "Valero Energy",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "VLTO",
    "name": "Veralto",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "VMC",
    "name": "Vulcan Materials Company",
    "sector": "Materials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "VRSK",
    "name": "Verisk Analytics",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "VRSN",
    "name": "Verisign",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "VRT",
    "name": "Vertiv",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "VRTX",
    "name": "Vertex Pharmaceuticals",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "VST",
    "name": "Vistra Corp.",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "VTR",
    "name": "Ventas",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "VTRS",
    "name": "Viatris",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "VZ",
    "name": "Verizon",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "WAB",
    "name": "Wabtec",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "WAT",
    "name": "Waters Corporation",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "WBD",
    "name": "Warner Bros. Discovery",
    "sector": "Communication Services",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "WDAY",
    "name": "Workday, Inc.",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "WDC",
    "name": "Western Digital",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "WEC",
    "name": "WEC Energy Group",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "WELL",
    "name": "Welltower",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "WFC",
    "name": "Wells Fargo",
    "sector": "Financials",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "WM",
    "name": "Waste Management",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "WMB",
    "name": "Williams Companies",
    "sector": "Energy",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "WMT",
    "name": "Walmart",
    "sector": "Consumer Staples",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "WRB",
    "name": "W. R. Berkley Corporation",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "WSM",
    "name": "Williams-Sonoma, Inc.",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "WST",
    "name": "West Pharmaceutical Services",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "WTW",
    "name": "Willis Towers Watson",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "WY",
    "name": "Weyerhaeuser",
    "sector": "Real Estate",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "WYNN",
    "name": "Wynn Resorts",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Mid Cap"
  },
  {
    "ticker": "XEL",
    "name": "Xcel Energy",
    "sector": "Utilities",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "XOM",
    "name": "ExxonMobil",
    "sector": "Energy",
    "marketCapTier": "Mega Cap"
  },
  {
    "ticker": "XYL",
    "name": "Xylem Inc.",
    "sector": "Industrials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "XYZ",
    "name": "Block, Inc.",
    "sector": "Financials",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "YUM",
    "name": "Yum! Brands",
    "sector": "Consumer Discretionary",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ZBH",
    "name": "Zimmer Biomet",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ZBRA",
    "name": "Zebra Technologies",
    "sector": "Information Technology",
    "marketCapTier": "Large Cap"
  },
  {
    "ticker": "ZTS",
    "name": "Zoetis",
    "sector": "Health Care",
    "marketCapTier": "Large Cap"
  }
];
